### PR TITLE
fix the warning and disable some printing

### PR DESCRIPTION
**Pull request by tingxingdong**
resolves #___

Summary of proposed changes:
-  
-  
-

### CODE REVIEW

**Comment by tingxingdong** [comment]
interesting. nvcc does not complain:  "(void)(rw==rw) always true". But hcc does.

**Comment by bragadeesh** [comment]
Hmmm, can you put inside macro
#ifdef __NVCC__
(void)(rw==rw);
#endif

**Comment by tingxingdong** [comment]
then hcc does not see this line at all. However, it rolls back to be  previous case: complain rw is defined but not used.

**Comment by bragadeesh** [comment]
OK, how about

Hmmm, can you put inside macro
#ifdef \_\_NVCC\_\_
(void)(rw==rw);
#else
(void)rw;
#endif

**Pull request merged**
